name: "Delta Lake Connectors Tests"
on: [push, pull_request]
jobs:
  build:
    name: "Run tests"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        scala: [2.12.8, 2.11.12]
    steps:
      - uses: actions/checkout@v2
      - name: install java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Cache Scala, SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2
            ~/.cache/coursier
            ~/.m2
          key: build-cache-with-scala_${{ matrix.scala }}
      - name: Run Scala Style tests on test sources
        run: build/sbt "++ ${{ matrix.scala }}" testScalastyle
      - name: Run sqlDeltaImport tests (Scala 2.12 only)
        run: build/sbt "++ ${{ matrix.scala }}" sqlDeltaImport/test
        if: matrix.scala != '2.11.12'
      - name: Run SBT tests
        shell: bash -l {0}
        run: |
          build/sbt "++ ${{ matrix.scala }} testScalastyle"
          build/sbt "++ ${{ matrix.scala }} standalone/test"
          build/sbt "++ ${{ matrix.scala }} testStandaloneCosmetic/test"
          build/sbt "++ ${{ matrix.scala }} compatibility/test"
          build/sbt "++ ${{ matrix.scala }} hiveMR/test"
          build/sbt "++ ${{ matrix.scala }} hiveTez/test"
          build/sbt "++ ${{ matrix.scala }} hive2MR/test"
          build/sbt "++ ${{ matrix.scala }} hive2Tez/test"
          build/sbt "++ ${{ matrix.scala }} flinkConnector/test"
